/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlybanhang;

import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author shypo
 */
public class MuaHangJFrame extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    /**
     * Creates new form MuaHangJFrame
     */
    public MuaHangJFrame() {
        // ... (Khởi tạo giao diện)      
            try {          
                initComponents();
                tableModel = new DefaultTableModel();
                tableMuaHang.setModel(tableModel);        
                loadData();
                }catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: " + e.getMessage());
            }  
    }
    //===============================
    private void themVaoGioHang() {
    int selectedRow = tableMuaHang.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm để thêm vào giỏ hàng!");
        return;
    }

    Object tenSanPhamObj = tableModel.getValueAt(selectedRow, 0);
    Object loaiSanPhamObj = tableModel.getValueAt(selectedRow, 1);
    Object giaTienObj = tableModel.getValueAt(selectedRow, 2);
    Object soLuongObj = tableModel.getValueAt(selectedRow, 3);

    // Kiểm tra null trước khi sử dụng
    if (tenSanPhamObj == null || loaiSanPhamObj == null || giaTienObj == null || soLuongObj == null) {
        JOptionPane.showMessageDialog(this, "Dữ liệu sản phẩm không hợp lệ!");
        return;
    }

    String tenSanPham = tenSanPhamObj.toString();
    String loaiSanPham = loaiSanPhamObj.toString();
    double giaTien = (giaTienObj instanceof Number) ? ((Number) giaTienObj).doubleValue() : Double.parseDouble(giaTienObj.toString());
    int soLuong = (soLuongObj instanceof Number) ? ((Number) soLuongObj).intValue() : Integer.parseInt(soLuongObj.toString());

    if (soLuong <= 0) {
        JOptionPane.showMessageDialog(this, "Sản phẩm này đã hết hàng!");
        return;
    }

    tableMuaHang.setValueAt(soLuong - 1, selectedRow, 3);

    DefaultTableModel modelGioHang = (DefaultTableModel) tableGioHang.getModel();
    boolean daTonTai = false;

    for (int i = 0; i < modelGioHang.getRowCount(); i++) {
        Object existingProduct = modelGioHang.getValueAt(i, 0);

        // Kiểm tra null trước khi gọi equals()
        if (existingProduct != null && existingProduct.equals(tenSanPham)) {
            int soLuongCu = (int) modelGioHang.getValueAt(i, 2);
            modelGioHang.setValueAt(soLuongCu + 1, i, 2);
            modelGioHang.setValueAt((soLuongCu + 1) * giaTien, i, 3);
            daTonTai = true;
            break;
        }
    }

    if (!daTonTai) {
        modelGioHang.addRow(new Object[]{tenSanPham, loaiSanPham, 1, giaTien});
    }
}
     //===================================================//
    
    private Connection getConnection() throws SQLException {
        String url = "jdbc:mysql://localhost:3306/qlbh";
        String username = "root";
        String password = "";
        return DriverManager.getConnection("jdbc:mysql://localhost:3306/qlbh", "root", "");
    }
    //=================================================//
    private void loadData() {
        tableModel.setColumnIdentifiers(new Object[]{"Tên Sản Phẩm", "Loại Sản Phẩm", "Giá tiền", "Số Lượng"});
        tableModel.setRowCount(0);

        try (Connection connection = getConnection();
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("SELECT * FROM SanPham")) {

            while (resultSet.next()) {
                Object[] row = {
                    resultSet.getString("ProductName"),
                    resultSet.getString("LoaiSanPham"), // Sửa thứ tự
                    resultSet.getDouble("Price"),
                    resultSet.getInt("StockQuantity")
                };
                tableModel.addRow(row);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }  

    //========================================================//
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMuaHang = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableGioHang = new javax.swing.JTable();
        buyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableMuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Sản Phẩm", "Mô Tả Sản Phẩm", "Giá Sản Phẩm", "Số Lượng Tồn Kho"
            }
        ));
        jScrollPane1.setViewportView(tableMuaHang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 788, 254));

        jButton3.setText("Thêm Vào Giỏ Hàng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 346, -1, -1));

        tableGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableGioHang);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 346, 421, 351));

        buyButton.setText("Mua Hàng");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(buyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 387, 136, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Danh Sách Sản Phẩm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 240, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Giỏ Hàng");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        themVaoGioHang();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_buyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuaHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuaHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuaHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuaHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuaHangJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableGioHang;
    private javax.swing.JTable tableMuaHang;
    // End of variables declaration//GEN-END:variables
}
